# 7일차 2024-04-25 p.47 ~ 50

## 아이템 9 try-finally 보다는 try-with-resources 를 사용하라

자바 라이브러리에는 close 메서드를 호출해 직접 닫아 줘야 하는 자원이 많다.
InputStream , OutputStream , java.sql.Connection 등이 좋은 예다.

자원 닫기는 클라이언트가 놓치기 쉬워서 예측할 수 없는 성능 문제로 이어지기도 한다.
이런 자원 중 상당수가 안전망으로 finalizer 를 활용하고 있지만 finalizer 는 그리 믿을만하지 못하다

전통적으로 자원이 제대로 닫힘을 보장하는 수단으로 try-finally 가 쓰였다.

예외가 발생하거나 메서드에서 반환되는 경우를 포함해서 말이다.

`try-finally - 더 이상 자원을 회수하는 최선의 방책이 아니다.`

```java
    static String firstLineOfFile(String path) throws IOException {
        BufferedReader br = new BufferedReader(new FileReader(path));
        try {
            return br.readLine();
        }finally {
            br.close();
        }
    }
```

나쁘지 않지만, 자원을 하나 더 사용한다면 어떨까?

`자원이 둘 이상이면 try-finally 방식은 너무 지저분하다 !`

```java
 static void copy(String src , String dst) throws IOException {
        InputStream in = new FileInputStream(src);
        try {
            OutputStream out  = new FileOutputStream(dst);
            try {
                
                byte[]  buf = new byte[BUFFER_SIZE];
                int n;
                while ((n = in.read(buf)) >= 0){
                    out.write(buf,0,n);
                }
            }finally {
                out.close();
            }
        }finally {
            in.close();
        }
    }
```

예외는 try  블록과 finally 블록 모두에서 발생할 수 있는데, 
예컨대 기기에 물리적인 문제가 생긴다면 
firstLineOfFile 메서드 안의 readLine 메서드가 예외를 던지고, 같은 이유로 close 메서드도  실패 할 것이다.

이런 상황이라면 두 번째 예외가 첫 번째 예외를 완전히 집어삼켜 버린다. 그러면 스택 추적 내역에
첫 번째 예외에 관한 정보는 남지 않게 되어, 실제 시스템에서의 디버깅을 몹시 어렵게 한다.

이러한 문제들은 자바 7이 투척한 try-with-resources 덕에 모두 해결되었디.

이 구조를 사용하려면 해당 자원이 AutoCloseable 인터페이스를 구현해야 한다. 

단순히 void 를 반환하는 close 메서드 하나만 덩그러니 정의한 인터페이스다.

자바 라이브러리와 서드파티 라이브러리들의 수많은 클래스와 인터페이스가 이미 AutoCloseable 을 구현하거나
확장해뒀다. 여러분도 닫아야 하는 자원을 뜻하는 클래스를 작성한다면 AutoCloseable 을 반드시 구현하기 바란다.

try-with-resources 를 사용해 재작성한 예시

`try-with-resources- 자원을 회수하는 최선책!`

```java
    static String firstLineOfFile(String path) throws IOException {
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            return br.readLine();
        }

    }

```

`복수의 자원을 처리하는 try-with-resources - 짧고 매혹적이다 !`

```java
  static void copy(String src, String dst) throws IOException {
        try (InputStream in = new FileInputStream(src);
             OutputStream out = new FileOutputStream(dst)) {
            byte[] buf = new byte[BUFFER_SIZE];
            int n;
            while ((n = in.read(buf)) >= 0)
                out.write(buf, 0, n);
        }

    }
```

try-with-resources 버전이 짧고 읽기 수월할 뿐 아니라 문제를 진단하기도 훨씬 좋다.

firstLineOfFile 메서드를 생각해보자.  readLine 과  close 호출 양쪽에서 예외가 발생하면,
close 에서 발생한 예외는 숨겨지고 readLine 에서 발생한 예외가 기록된다. 

이처럼 실전에서는 프로그래머에게 보여줄 예외 하나만 보전되고 여러 개의 다른 예외가 숨겨질 수도 있다.
이렇게 숨겨진 예외들도 그냥 버려지지는 않고, 스택 추적 내역에 '숨겨졌다(suppressed)'는 꼬리표를 달고
출력된다. 또한, 자바7에서 Throwable 에 추가된 getSuppressed 메서드를 이용하면 프로그램 코드에서
가져올 수도 있다.

보통의 try-finally 처럼 try-with-resources 에서도 catch 절을 쓸 수 있다.
catch 절 덕분에 try 문을 더 중첩하지 않고도 다수의 예외를 처리할 수 있다.

다음 코드에서는 firstLineOfFile 메서드를 살짝 수정하여 파일을 열거나 데이터를 읽지 못했을 때
예외를 던지는 대신 기본값을 반환하도록 해봤다. 

예가 살짝 어색하더라도 이해해주기 바란다.


`try-with-resources 를 catch 절과 함께 쓰는 모습`

```java
    static String firstLineOfFile(String path, String defaultVal) {
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            return br.readLine();
        } catch (IOException e) {
            return defaultVal;
        }
    }
```


> **핵심 정리** <br/>
> 꼭 회수 해야 하는 자원을 다룰 때는 try-finally 말고, try-with-resources 를 사용하자.
> 예외는 없다. 코드는 더 짧고 분명해지고, 만들어지는 예외 정보도 훨씬 유용하다. 
> try-finally 로 작성하면 실용적이지 못할 만큼 코드가 지저분해지는 경우라도, try-with-resources 로는 정확하고 쉽게
> 자원을 회수 할 수 있다.